/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_binarybrain_hw_i2c_I2CDriver */

#ifndef _Included_it_binarybrain_hw_i2c_I2CDriver
#define _Included_it_binarybrain_hw_i2c_I2CDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef it_binarybrain_hw_i2c_I2CDriver_MIN_PRIORITY
#define it_binarybrain_hw_i2c_I2CDriver_MIN_PRIORITY 1L
#undef it_binarybrain_hw_i2c_I2CDriver_NORM_PRIORITY
#define it_binarybrain_hw_i2c_I2CDriver_NORM_PRIORITY 5L
#undef it_binarybrain_hw_i2c_I2CDriver_MAX_PRIORITY
#define it_binarybrain_hw_i2c_I2CDriver_MAX_PRIORITY 10L
/*
 * Class:     it_binarybrain_hw_i2c_I2CDriver
 * Method:    nativeOpenDeviceFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_binarybrain_hw_i2c_I2CDriver_nativeOpenDeviceFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_binarybrain_hw_i2c_I2CDriver
 * Method:    nativeCloseDeviceFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_binarybrain_hw_i2c_I2CDriver_nativeCloseDeviceFile
  (JNIEnv *, jobject);

/*
 * Class:     it_binarybrain_hw_i2c_I2CDriver
 * Method:    nativeWriteByte
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_it_binarybrain_hw_i2c_I2CDriver_nativeWriteByte
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     it_binarybrain_hw_i2c_I2CDriver
 * Method:    nativeReadByte
 * Signature: (BB)B
 */
JNIEXPORT jbyte JNICALL Java_it_binarybrain_hw_i2c_I2CDriver_nativeReadByte
  (JNIEnv *, jobject, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
