/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_binarybrain_hw_I2CDriver */

#ifndef _Included_it_binarybrain_hw_I2CDriver
#define _Included_it_binarybrain_hw_I2CDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    openFileDescriptor
 * Signature: (Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_it_binarybrain_hw_I2CDriver_openFileDescriptor
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    closeFileDescriptor
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_it_binarybrain_hw_I2CDriver_closeFileDescriptor
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    writeByte
 * Signature: (IBBZ)V
 */
JNIEXPORT void JNICALL Java_it_binarybrain_hw_I2CDriver_writeByte
  (JNIEnv *, jobject, jint, jbyte, jbyte, jboolean);

/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    readByte
 * Signature: (IBZ)B
 */
JNIEXPORT jbyte JNICALL Java_it_binarybrain_hw_I2CDriver_readByte
  (JNIEnv *, jobject, jint, jbyte, jboolean);

#ifdef __cplusplus
}
#endif
#endif
