/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_binarybrain_hw_I2CDriver */

#ifndef _Included_it_binarybrain_hw_I2CDriver
#define _Included_it_binarybrain_hw_I2CDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    openFileDescriptor
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_it_binarybrain_hw_I2CDriver_openFileDescriptor
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    writeByte
 * Signature: (BB)V
 */
JNIEXPORT void JNICALL Java_it_binarybrain_hw_I2CDriver_writeByte
  (JNIEnv *, jobject, jbyte, jbyte);

/*
 * Class:     it_binarybrain_hw_I2CDriver
 * Method:    readByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_it_binarybrain_hw_I2CDriver_readByte
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
